apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ .Values.rbac.clusterrole.metadata.name }}-rolebinding
subjects:
  - kind: ServiceAccount
    name: {{ include "sshd.serviceAccountName" . }}
    namespace: {{ .Release.Namespace | quote }}
roleRef:
  kind: ClusterRole
  name: {{ .Values.rbac.clusterrole.metadata.name }}
  apiGroup: "rbac.authorization.k8s.io"
