apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ .Values.rbac.role.metadata.name }}-rolebinding
subjects:
  - kind: ServiceAccount
    name: {{ include "sshd.serviceAccountName" . }}
roleRef:
  kind: Role
  name: {{ .Values.rbac.role.name }}
  apiGroup: "rbac.authorization.k8s.io"
