apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ .Values.rbac.clusterrole.metadata.name }}
  {{- if .Values.rbac.clusterrole.rules }}
rules:
  {{- range .Values.rbac.clusterrole.rules }}
  - apiGroups:
    {{- range .apiGroups }}
    - {{ . | quote }}
    {{- end }}
    resources:
    {{- range .resources }}
    - {{ . | quote }}
    {{- end }}
    verbs:
    {{- range .verbs }}
    - {{ . | quote }}
    {{- end }}
  {{- end }}
  {{- end }}