apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ .Values.rbac.role.metadata.name }}-rolebinding
  namespace: {{ .Release.Namespace | quote }}
subjects:
  - kind: ServiceAccount
    name: {{ include "sshd.serviceAccountName" . }}
roleRef:
  kind: Role
  name: {{ .Values.rbac.role.metadata.name }}
  apiGroup: "rbac.authorization.k8s.io"
